extends:
  - "@commitlint/config-conventional"
rules:
  # Lower lengths to 72 per widely accepted "best practice", and to play ball
  # with what many tools including git itself expect when supporting 80 char
  # terminal widths. They may add indentation, labels and the like on the left.
  header-max-length: [2, "always", 72]
  # Make exceeding 72 chars a warning rather than error in body and footer,
  # because e.g. URLs are often easily longer than that, and they should not
  # be broken/wrapped.
  footer-max-line-length: [1, "always", 72]
  body-max-line-length: [1, "always", 72]
  # Make missing empty line between header and body an error.
  body-leading-blank: [2, "always"]
