name: checks

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ">=1.15"  # for shfmt
      - uses: pre-commit/action@v2.0.0

  distcheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dist: alpine
          - dist: centos7
          - dist: debian10
          - dist: debian10
            bsd: true
            network: none
          # https://bugzilla.redhat.com/1910208
          #- dist: fedoradev
          - dist: ubuntu14
    steps:
      - uses: actions/checkout@v2
      # A "container" workflow config would be cleaner here, but comes with
      # some restrictions/oddities: changes root's $HOME to /github/home
      # without changing the actual home dir that can cause some problems,
      # and does not provide a way to run with --network none.
      - run: >-
          docker run
          --rm
          --tty
          --env CI=true
          --env DIST=${{matrix.dist}}
          --env BSD=${{matrix.bsd}}
          --env NETWORK=$NETWORK
          ${NETWORK:+--network $NETWORK}
          --volume $PWD:/usr/src/bash-completion
          --workdir /usr/src/bash-completion
          vskytta/bash-completion:${{matrix.dist}}
          test/docker-script.sh
        env:
          NETWORK: ${{matrix.network}}

  # TODO releases config
  # - for tags [0-9]+.[0-9]+ in scop/bash-completion
  # - tarball should be in bash-completion-${GITHUB_REF##*/}.tar.xz
